// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.11
// source: innermessages.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname     string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UserPortrait string `protobuf:"bytes,3,opt,name=userPortrait,proto3" json:"userPortrait,omitempty"`
}

func (x *UserRegReq) Reset() {
	*x = UserRegReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_innermessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegReq) ProtoMessage() {}

func (x *UserRegReq) ProtoReflect() protoreflect.Message {
	mi := &file_innermessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegReq.ProtoReflect.Descriptor instead.
func (*UserRegReq) Descriptor() ([]byte, []int) {
	return file_innermessages_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserRegReq) GetUserPortrait() string {
	if x != nil {
		return x.UserPortrait
	}
	return ""
}

type UserReqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *UserReqResp) Reset() {
	*x = UserReqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_innermessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserReqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReqResp) ProtoMessage() {}

func (x *UserReqResp) ProtoReflect() protoreflect.Message {
	mi := &file_innermessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReqResp.ProtoReflect.Descriptor instead.
func (*UserReqResp) Descriptor() ([]byte, []int) {
	return file_innermessages_proto_rawDescGZIP(), []int{1}
}

func (x *UserReqResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserReqResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_innermessages_proto protoreflect.FileDescriptor

var file_innermessages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75,
	0x73, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x62,
	0x6f, 0x62, 0x6a, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_innermessages_proto_rawDescOnce sync.Once
	file_innermessages_proto_rawDescData = file_innermessages_proto_rawDesc
)

func file_innermessages_proto_rawDescGZIP() []byte {
	file_innermessages_proto_rawDescOnce.Do(func() {
		file_innermessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_innermessages_proto_rawDescData)
	})
	return file_innermessages_proto_rawDescData
}

var file_innermessages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_innermessages_proto_goTypes = []interface{}{
	(*UserRegReq)(nil),  // 0: UserRegReq
	(*UserReqResp)(nil), // 1: UserReqResp
}
var file_innermessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_innermessages_proto_init() }
func file_innermessages_proto_init() {
	if File_innermessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_innermessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRegReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_innermessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserReqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_innermessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_innermessages_proto_goTypes,
		DependencyIndexes: file_innermessages_proto_depIdxs,
		MessageInfos:      file_innermessages_proto_msgTypes,
	}.Build()
	File_innermessages_proto = out.File
	file_innermessages_proto_rawDesc = nil
	file_innermessages_proto_goTypes = nil
	file_innermessages_proto_depIdxs = nil
}
